/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Examples.Factorization.Common
public import NN.Spec.Core.Tensor.KernelMatrix
public import NN.Spec.Core.Tensor.KernelLoss
public import NN.Spec.Core.Tensor.KernelGrad
public import NN.Spec.Core.Tensor.Optimizers
public import NN.Spec.Core.Tensor.CondVar
public import NN.Spec.Core.Tensor.Factorizations
meta import NN.Examples.Factorization.Common
meta import NN.Spec.Core.Tensor.KernelMatrix
meta import NN.Spec.Core.Tensor.KernelLoss
meta import NN.Spec.Core.Tensor.KernelGrad
meta import NN.Spec.Core.Tensor.Optimizers
meta import NN.Spec.Core.Tensor.CondVar
meta import NN.Spec.Core.Tensor.Factorizations

/-!
# KernelFlows parity harness (S8) — the shared end-to-end fixture

S8 is the **parity harness** (the Year-2 deliverable): one realistic problem driven through the *whole*
KernelFlows / Computational-Hypergraph-Discovery numerical core, with every deterministic stage checked
against a golden tile generated by the reference implementations, and the *stochastic* edge-selection
test checked at the level of its **decision** (the recovered kernel/edge set), which is what CHD actually
consumes.

Steps S1–S7 each verified a stage on its own fixture. S8 ties them together: a single fixture flows
`kernel build → losses → gradients → optimizer step → conditional variance → eig → Z-test`, so the
harness exercises the *composition*, not just the pieces. The deterministic stages
([`Deterministic`](Deterministic.lean)) match the golden to the float-path tolerance `1e-8`; the
stochastic Z-test ([`Stochastic`](Stochastic.lean)) matches at the **decision** level — the recovered
edge survives across independent random null tiles (RNG-invariance), with the deterministic thresholds
themselves also matching to `1e-8`.

## The shared fixture

The kernel tile is the **verbatim KernelFlows.jl** `kernel_matrix(::UnaryKernel{Matern32}, …)` on the
S1 data `X` (4 points in ℝ², `nXlinear = 1` ⟺ `wlin = [1,0]`, `logθ = [0, 0.5, −1, −3]`); the Lean
exact-distance build reproduces it to `~10⁻¹⁵` (the `5·eps` distance floor moves `K` only through the
Matérn flat top — see S1). Every downstream golden (losses, gradients, optimizer step, conditional
variance, Z-test) is computed from the *same* fixture with the exact arithmetic the Lean specs
implement, validated against KernelFlows.jl `loss_functions.jl` / `kernel_functions_analytic.jl` /
`optimizers.jl` / `conditional_variance.jl`.

The values are sorry/admit/omega-free executable checks over `Float`, the 64-bit runtime scalar.
-/

@[expose] public section

namespace NN.Examples.KernelFlows.Parity

open NN.Examples.Factorization (assertLt assertGe assertApproxEq)

/-! ### The shared fixture (the KernelFlows.jl S1 tile + a label and a test vector) -/

/-- Sample matrix `X` — 4 points in ℝ² (the verbatim S1 / KernelFlows.jl data). -/
def X : Fin 4 → Fin 2 → Float :=
  fun i k => ([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0], [2.0, 1.0]].getD i.val []).getD k.val 0.0

/-- Linear-term column mask `wlin = [1,0]` — selects the first feature, i.e. KernelFlows' `nXlinear = 1`. -/
def wlin : Fin 2 → Float := fun k => [1.0, 0.0].getD k.val 0.0

/-- Log-hyperparameters `logθ = [log a, log b, log L, log nugget] = [0, 0.5, −1, −3]`. -/
def logθ : Fin 4 → Float := fun i => [0.0, 0.5, -1.0, -3.0].getD i.val 0.0

/-- Labels `y`. -/
def yv : Fin 4 → Float := fun i => [1.0, -0.5, 0.8, 0.2].getD i.val 0.0

/-- The `ρ_KF` center embedding — the leading `nc = 2` indices into the `n = 4` samples. -/
def e : Fin 2 → Fin 4 := Fin.castLE (by decide)

/-- A cross-covariance test vector `m = k(x*, X)` for the conditional-variance stage. -/
def mtest : Fin 4 → Float := fun i => [1.0, 0.5, 0.2, 0.0].getD i.val 0.0

/-- The shared kernel matrix `Ω = K(logθ)` (function form, for losses/gradients). -/
def Ω : Fin 4 → Fin 4 → Float := Spec.kernelMatrixMatern32Fn X wlin logθ

/-- `Ω` as a tensor, for the eigendecomposition / conditional-variance specs. -/
def Ωt : Spec.Tensor Float (.dim 4 (.dim 4 .scalar)) := Spec.ofMatFn Ω

/-- The closed-form kernel derivative tile `∂Ω/∂logθ_c` (ported `Matern32_αgrad!`). -/
def Hc (c : Fin 4) : Fin 4 → Fin 4 → Float := Spec.kernelMatrixMatern32GradFn X wlin logθ c

/-! ### Parity assertion helpers -/

/-- The deterministic float-path parity tolerance. -/
def parityTol : Float := 1e-8

/-- **Scalar parity**: the Lean spec value matches the reference golden to `parityTol`. A thin,
parity-flavored wrapper over `assertApproxEq` (the message reads as "Lean vs golden Δ"). -/
def assertParity (name : String) (lean golden : Float) (tol : Float := parityTol) : IO Unit :=
  assertApproxEq s!"{name} (Lean vs KernelFlows.jl golden)" lean golden tol

/-- Max entrywise `|lean − golden|` over a `4×4` tile (Lean function vs golden function). -/
def tileErr (A B : Fin 4 → Fin 4 → Float) : Float :=
  (List.finRange 4).foldl (fun acc i =>
    (List.finRange 4).foldl (fun a j => max a (Float.abs (A i j - B i j))) acc) 0.0

/-- Max `|leanᵢ − goldenᵢ|` over a length-4 vector given as a list of golden entries. -/
def vecErr (lean : Fin 4 → Float) (golden : List Float) : Float :=
  (List.finRange 4).foldl (fun acc i => max acc (Float.abs (lean i - golden.getD i.val 0.0))) 0.0

/-- Build a `4×4` golden tile from a row-major nested list (for `∂Ω/∂logθ_c` parity). -/
def tileOf (rows : List (List Float)) : Fin 4 → Fin 4 → Float :=
  fun i j => (rows.getD i.val []).getD j.val 0.0

/-- **Decision parity**: assert a `Bool` edge/kernel decision equals the golden decision. -/
def assertDecision (name : String) (lean golden : Bool) : IO Unit :=
  if lean == golden then
    IO.println s!"{name}: OK (decision = {lean}, matches golden)"
  else
    throw (IO.userError s!"{name}: FAIL (Lean decision {lean} ≠ golden {golden})")

end NN.Examples.KernelFlows.Parity
