/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Runtime.PyTorch.Export.Core

/-!
# PyTorch `nn.Module` Graph Capture Adapter

This module emits the Python side of the model-import bridge:

```text
PyTorch nn.Module
  --torch.export / FX capture-->
TorchLean graph JSON (`torchlean.ir.v1`)
  --NN.Runtime.PyTorch.Import.TorchExport.parseGraph-->
NN.IR.Graph
```

Why generate a Python adapter instead of parsing PyTorch objects in Lean?

- PyTorch checkpoints are Python/Pickle/zip artifacts; PyTorch is the external loader that knows
  how to read them.
- `torch.export` and FX already know how to inspect PyTorch programs.
- Lean should receive a small, explicit artifact and then validate it with TorchLean's own IR
  checkers.

The generated adapter is conservative by design. It lowers only ops that already exist in
`NN.IR.OpKind`; unsupported operators fail with a clear message. This is exactly the behavior we
want for verification: better to reject a model than silently erase semantics.

References:
- `torch.export`: `https://docs.pytorch.org/docs/stable/user_guide/torch_compiler/export.html`
- `torch.fx`: `https://docs.pytorch.org/docs/stable/fx.html`
-/

@[expose] public section

namespace Export
namespace PyTorch
namespace TorchExport

open Export.PyTorch

/-- Options for the generated PyTorch graph-capture script. -/
structure GraphBridgeOptions where
  /-- Name of the Python helper function emitted into the script. -/
  functionName : String := "export_torchlean_graph_json"
  /-- If true, use `torch.export.export` first and fall back to FX symbolic tracing. -/
  preferTorchExport : Bool := true
  /-- If true, include raw PyTorch target strings in each node for debugging. -/
  includeDebugTargets : Bool := true
deriving Repr

/--
Emit a Python script that captures a PyTorch module and writes TorchLean graph JSON.

The generated script expects a Python file containing a zero-argument model constructor or class:

```bash
python export_torchlean_graph.py my_model.py MyModel out_graph.json --example-shape 1,4
```

The first implementation target is the shared IR subset: elementwise ops, matmul, reductions,
reshape/permute/flatten/concat, softmax, layernorm, and simple pooling/conv metadata when PyTorch
exposes enough static arguments. Linear layers can appear either as `aten.linear` or as lower-level
`matmul/add` depending on PyTorch's graph capture.
-/
def generateGraphBridgeScript (opts : GraphBridgeOptions := {}) : String :=
  joinLines
    #[ "import argparse"
    , "import importlib.util"
    , "import json"
    , "import operator"
    , "from pathlib import Path"
    , "import torch"
    , "import torch.nn as nn"
    , "import torch.nn.functional as F"
    , ""
    , "FORMAT = \"torchlean.ir.v1\""
    , ""
    , "def _shape_of(value):"
    , indentFour "if hasattr(value, \"shape\"):"
    , indentEight "return [int(x) for x in tuple(value.shape)]"
    , indentFour "if isinstance(value, (tuple, list)) and value and hasattr(value[0], \"shape\"):"
    , indentEight "return [int(x) for x in tuple(value[0].shape)]"
    , indentFour "return []"
    , ""
    , "def _node_shape(node):"
    , indentFour "return _shape_of(node.meta.get(\"val\", node.meta.get(\"tensor_meta\")))"
    , ""
    , "def _shape_from_arg(arg):"
    , indentFour "return _node_shape(arg) if hasattr(arg, \"meta\") else []"
    , ""
    , "def _tuple_shapes_of_node(node):"
    , indentFour "val = node.meta.get(\"val\", None)"
    , indentFour "if isinstance(val, (tuple, list)) and not hasattr(val, \"shape\"):"
    , indentEight "return [_shape_of(x) for x in val]"
    , indentFour "tm = node.meta.get(\"tensor_meta\", None)"
    , indentFour "if hasattr(tm, \"shape\"):"
    , indentEight "return []"
    , indentFour "if isinstance(tm, (tuple, list)):"
    , indentEight "return [_shape_of(x) for x in tm]"
    , indentFour "return []"
    , ""
    , "def _is_getitem(node):"
    , indentFour "return node.target is operator.getitem or _target_name(node.target) == \"<built-in function getitem>\""
    , ""
    , "def _is_getattr(node):"
    , indentFour "return node.target is getattr or _target_name(node.target) == \"<built-in function getattr>\""
    , ""
    , "def _tuple_kind(node, model=None):"
    , indentFour "if node.op == \"call_module\" and model is not None:"
    , indentEight "mod = model.get_submodule(str(node.target))"
    , indentEight "if isinstance(mod, nn.MultiheadAttention):"
    , indentEight "    if mod.add_zero_attn or mod.bias_k is not None or mod.bias_v is not None:"
    , indentEight "        raise NotImplementedError(\"nn.MultiheadAttention with added bias/zero sequence entries is outside the current TorchLean IR import subset\")"
    , indentEight "    if mod.kdim != mod.embed_dim or mod.vdim != mod.embed_dim:"
    , indentEight "        raise NotImplementedError(\"nn.MultiheadAttention with kdim/vdim different from embed_dim is outside the current TorchLean IR import subset\")"
    , indentEight "    if node.kwargs.get(\"attn_mask\", None) is not None or node.kwargs.get(\"key_padding_mask\", None) is not None:"
    , indentEight "        raise NotImplementedError(\"masked nn.MultiheadAttention needs an explicit TorchLean hard-mask lowering\")"
    , indentEight "    if bool(node.kwargs.get(\"is_causal\", False)):"
    , indentEight "        raise NotImplementedError(\"causal nn.MultiheadAttention needs an explicit TorchLean hard-mask lowering\")"
    , indentEight "    return {"
    , indentEight "        \"kind\": \"multihead_attention\","
    , indentEight "        \"embed_dim\": int(mod.embed_dim),"
    , indentEight "        \"num_heads\": int(mod.num_heads),"
    , indentEight "        \"batch_first\": bool(mod.batch_first),"
    , indentEight "        \"dropout_zero\": bool(float(mod.dropout) == 0.0),"
    , indentEight "        \"bias\": bool(mod.in_proj_bias is not None),"
    , indentEight "    }"
    , indentFour "return {\"kind\": \"py_tuple\"}"
    , ""
    , "def _load_model(module_path: str, ctor_name: str):"
    , indentFour "spec = importlib.util.spec_from_file_location(\"torchlean_user_model\", module_path)"
    , indentFour "if spec is None or spec.loader is None:"
    , indentEight "raise RuntimeError(f\"could not load Python module from {module_path}\")"
    , indentFour "mod = importlib.util.module_from_spec(spec)"
    , indentFour "spec.loader.exec_module(mod)"
    , indentFour "ctor = getattr(mod, ctor_name)"
    , indentFour "model = ctor()"
    , indentFour "model.eval()"
    , indentFour "return model"
    , ""
    , "def _target_name(target):"
    , indentFour "return str(target).replace(\"torch.ops.\", \"\")"
    , ""
    , "def _node_refs(obj, node_to_id):"
    , indentFour "refs = []"
    , indentFour "def visit(x):"
    , indentEight "if isinstance(x, torch.fx.Node):"
    , indentEight "    ref = node_to_id.get(x, None)"
    , indentEight "    if ref is not None:"
    , indentEight "        refs.append(ref)"
    , indentEight "elif isinstance(x, (tuple, list)):"
    , indentEight "    for y in x: visit(y)"
    , indentEight "elif isinstance(x, dict):"
    , indentEight "    for y in x.values(): visit(y)"
    , indentFour "visit(obj)"
    , indentFour "return refs"
    , ""
    , "def _spatial_tuple(x, rank, default):"
    , indentFour "if x is None: return [int(default)] * rank"
    , indentFour "if isinstance(x, int): return [int(x)] * rank"
    , indentFour "if isinstance(x, (tuple, list)) and len(x) == rank: return [int(v) for v in x]"
    , indentFour "raise NotImplementedError(f\"expected an integer or length-{rank} spatial tuple, got {x!r}\")"
    , ""
    , "def _tensor_values(value):"
    , indentFour "return value.detach().cpu().tolist()"
    , ""
    , "_TENSOR_VALUES = {}"
    , ""
    , "def _resolve_tensor(value):"
    , indentFour "if isinstance(value, torch.Tensor): return value"
    , indentFour "if isinstance(value, torch.fx.Node) and value.name in _TENSOR_VALUES: return _TENSOR_VALUES[value.name]"
    , indentFour "raise NotImplementedError(f\"could not resolve tensor argument {value!r} into the exported payload\")"
    , ""
    , "def _flatten_kind(input_shape, output_shape):"
    , indentFour "if len(output_shape) == 1:"
    , indentEight "return {\"kind\": \"flatten\", \"value_shape\": input_shape}"
    , indentFour "return {\"kind\": \"reshape\", \"in_shape\": input_shape, \"out_shape\": output_shape}"
    , ""
    , "def _normalize_axis(axis, rank):"
    , indentFour "axis = int(axis)"
    , indentFour "axis = axis + rank if axis < 0 else axis"
    , indentFour "if axis < 0 or axis >= rank:"
    , indentEight "raise NotImplementedError(f\"axis {axis} is outside rank {rank}\")"
    , indentFour "return axis"
    , ""
    , "def _reduction_axes(axis, rank, op_name):"
    , indentFour "raw = range(rank) if axis is None else axis if isinstance(axis, (tuple, list)) else (axis,)"
    , indentFour "axes = [_normalize_axis(value, rank) for value in raw]"
    , indentFour "if len(set(axes)) != len(axes):"
    , indentEight "raise NotImplementedError(f\"{op_name} has duplicate reduction axes {axes}\")"
    , indentFour "return axes"
    , ""
    , "def _lower_kind(node, model=None):"
    , indentFour "name = _target_name(node.target)"
    , indentFour "args = node.args"
    , indentFour "kwargs = dict(node.kwargs)"
    , indentFour "axis = kwargs.get(\"dim\", kwargs.get(\"axis\", None))"
    , indentFour "if axis is None and len(args) > 1: axis = args[1]"
    , indentFour "if node.op == \"call_module\" and model is not None:"
    , indentEight "mod = model.get_submodule(str(node.target))"
    , indentEight "if isinstance(mod, nn.Linear): return {\"kind\": \"linear\"}"
    , indentEight "if isinstance(mod, nn.ReLU):"
    , indentEight "    if mod.inplace: raise NotImplementedError(\"in-place nn.ReLU mutation is outside the pure TorchLean graph contract\")"
    , indentEight "    return {\"kind\": \"relu\"}"
    , indentEight "if isinstance(mod, nn.Tanh): return {\"kind\": \"tanh\"}"
    , indentEight "if isinstance(mod, nn.Sigmoid): return {\"kind\": \"sigmoid\"}"
    , indentEight "if isinstance(mod, nn.Softmax):"
    , indentEight "    return {\"kind\": \"softmax\", \"axis\": _normalize_axis(mod.dim, len(_node_shape(node)))}"
    , indentEight "if isinstance(mod, nn.Flatten):"
    , indentEight "    return _flatten_kind(_shape_from_arg(args[0]) if args else [], _node_shape(node))"
    , indentEight "if isinstance(mod, nn.LayerNorm):"
    , indentEight "    rank = len(_node_shape(node))"
    , indentEight "    norm_rank = len(tuple(mod.normalized_shape))"
    , indentEight "    gamma = mod.weight if mod.weight is not None else torch.ones(mod.normalized_shape)"
    , indentEight "    beta = mod.bias if mod.bias is not None else torch.zeros(mod.normalized_shape)"
    , indentEight "    return {\"kind\": \"layernorm\", \"axis\": max(0, rank - norm_rank), \"eps\": float(mod.eps), \"gamma\": _tensor_values(gamma), \"beta\": _tensor_values(beta)}"
    , indentEight "if isinstance(mod, (nn.Conv1d, nn.Conv2d, nn.Conv3d)):"
    , indentEight "    rank = len(tuple(mod.kernel_size))"
    , indentEight "    input_rank = len(_shape_from_arg(args[0])) if args else 0"
    , indentEight "    if input_rank not in (rank + 1, rank + 2): raise NotImplementedError(f\"convolution expected rank {rank + 1} or {rank + 2}, got {input_rank}\")"
    , indentEight "    channel_axis = input_rank - rank - 1"
    , indentEight "    if mod.padding_mode != \"zeros\": raise NotImplementedError(f\"convolution padding_mode={mod.padding_mode!r} is outside the current TorchLean IR import subset\")"
    , indentEight "    padding = _spatial_tuple(mod.padding, rank, 0)"
    , indentEight "    return {\"kind\": \"conv\", \"spatial_rank\": rank, \"kernel\": _spatial_tuple(mod.kernel_size, rank, 1), \"stride\": _spatial_tuple(mod.stride, rank, 1), \"padding\": padding, \"padding_after\": padding, \"dilation\": _spatial_tuple(mod.dilation, rank, 1), \"groups\": int(mod.groups), \"channel_axis\": channel_axis, \"in_channels\": int(mod.in_channels), \"out_channels\": int(mod.out_channels)}"
    , indentEight "if isinstance(mod, (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d)):"
    , indentEight "    if not mod.track_running_stats or mod.running_mean is None or mod.running_var is None:"
    , indentEight "        raise NotImplementedError(\"nn.BatchNorm2d without running statistics has batch-dependent semantics, not TorchLean eval-mode BatchNorm semantics\")"
    , indentEight "    gamma = mod.weight if mod.weight is not None else torch.ones(mod.num_features)"
    , indentEight "    beta = mod.bias if mod.bias is not None else torch.zeros(mod.num_features)"
    , indentEight "    return {\"kind\": \"batch_norm_eval\", \"channel_axis\": 1, \"channels\": int(mod.num_features), \"eps\": float(mod.eps), \"gamma\": _tensor_values(gamma), \"beta\": _tensor_values(beta), \"mean\": _tensor_values(mod.running_mean), \"var\": _tensor_values(mod.running_var)}"
    , indentEight "if isinstance(mod, (nn.MaxPool1d, nn.MaxPool2d, nn.MaxPool3d)):"
    , indentEight "    rank = 1 if isinstance(mod, nn.MaxPool1d) else 2 if isinstance(mod, nn.MaxPool2d) else 3"
    , indentEight "    if _spatial_tuple(mod.dilation, rank, 1) != [1] * rank: raise NotImplementedError(\"dilated max pooling is outside the current TorchLean IR import subset\")"
    , indentEight "    if mod.ceil_mode: raise NotImplementedError(\"max pooling with ceil_mode=True is outside the current TorchLean IR import subset\")"
    , indentEight "    if mod.return_indices: raise NotImplementedError(\"max pooling with return_indices=True produces a tuple outside the current pooling lowering\")"
    , indentEight "    return {\"kind\": \"max_pool\", \"spatial_rank\": rank, \"kernel\": _spatial_tuple(mod.kernel_size, rank, 1), \"stride\": _spatial_tuple(mod.stride if mod.stride is not None else mod.kernel_size, rank, 1), \"padding\": _spatial_tuple(mod.padding, rank, 0)}"
    , indentEight "if isinstance(mod, (nn.AvgPool1d, nn.AvgPool2d, nn.AvgPool3d)):"
    , indentEight "    rank = 1 if isinstance(mod, nn.AvgPool1d) else 2 if isinstance(mod, nn.AvgPool2d) else 3"
    , indentEight "    if mod.ceil_mode: raise NotImplementedError(\"average pooling with ceil_mode=True is outside the current TorchLean IR import subset\")"
    , indentEight "    if getattr(mod, 'divisor_override', None) is not None: raise NotImplementedError(\"average pooling with divisor_override is outside the current TorchLean IR import subset\")"
    , indentEight "    padding = _spatial_tuple(mod.padding, rank, 0)"
    , indentEight "    if any(padding) and not mod.count_include_pad: raise NotImplementedError(\"padded average pooling with count_include_pad=False is outside the current TorchLean IR import subset\")"
    , indentEight "    return {\"kind\": \"avg_pool\", \"spatial_rank\": rank, \"kernel\": _spatial_tuple(mod.kernel_size, rank, 1), \"stride\": _spatial_tuple(mod.stride if mod.stride is not None else mod.kernel_size, rank, 1), \"padding\": padding}"
    , indentFour "if name in (\"aten.add.Scalar\", \"aten.sub.Scalar\", \"aten.mul.Scalar\"):"
    , indentEight "raise NotImplementedError(f\"{name} needs an explicit scalar constant/broadcast lowering\")"
    , indentFour "if name == \"aten.add.Tensor\" or node.target is operator.add:"
    , indentEight "alpha = kwargs.get(\"alpha\", args[2] if len(args) > 2 else 1)"
    , indentEight "if alpha != 1: raise NotImplementedError(\"torch.add with alpha != 1 is outside the current TorchLean IR import subset\")"
    , indentEight "return {\"kind\": \"add\"}"
    , indentFour "if name == \"aten.sub.Tensor\" or node.target is operator.sub:"
    , indentEight "alpha = kwargs.get(\"alpha\", args[2] if len(args) > 2 else 1)"
    , indentEight "if alpha != 1: raise NotImplementedError(\"torch.sub with alpha != 1 is outside the current TorchLean IR import subset\")"
    , indentEight "return {\"kind\": \"sub\"}"
    , indentFour "if name == \"aten.mul.Tensor\" or node.target is operator.mul: return {\"kind\": \"mul_elem\"}"
    , indentFour "if name.startswith(\"aten.relu\") or node.target is torch.relu or node.target is F.relu: return {\"kind\": \"relu\"}"
    , indentFour "if name.startswith(\"aten.tanh\") or node.target is torch.tanh: return {\"kind\": \"tanh\"}"
    , indentFour "if name.startswith(\"aten.sigmoid\") or node.target is torch.sigmoid: return {\"kind\": \"sigmoid\"}"
    , indentFour "if name.startswith(\"aten.exp\") or node.target is torch.exp: return {\"kind\": \"exp\"}"
    , indentFour "if name.startswith(\"aten.log\") or node.target is torch.log: return {\"kind\": \"log\"}"
    , indentFour "if name.startswith(\"aten.sin\") or node.target is torch.sin: return {\"kind\": \"sin\"}"
    , indentFour "if name.startswith(\"aten.cos\") or node.target is torch.cos: return {\"kind\": \"cos\"}"
    , indentFour "if name.startswith(\"aten.abs\") or node.target is torch.abs: return {\"kind\": \"abs\"}"
    , indentFour "if name.startswith(\"aten.sqrt\") or node.target is torch.sqrt: return {\"kind\": \"sqrt\"}"
    , indentFour "if name.startswith(\"aten.reciprocal\"): return {\"kind\": \"inv\"}"
    , indentFour "if name.startswith(\"aten.maximum\") or node.target is torch.maximum: return {\"kind\": \"max_elem\"}"
    , indentFour "if name.startswith(\"aten.minimum\") or node.target is torch.minimum: return {\"kind\": \"min_elem\"}"
    , indentFour "if name.startswith(\"aten.matmul\") or name.startswith(\"aten.mm\") or node.target is torch.matmul: return {\"kind\": \"matmul\"}"
    , indentFour "if name.startswith(\"aten.sum\") or name.startswith(\"aten.mean\") or name in (\"sum\", \"mean\") or node.target in (torch.sum, torch.mean):"
    , indentEight "input_rank = len(_shape_from_arg(args[0])) if args else len(_node_shape(node))"
    , indentEight "reduction_axes = _reduction_axes(axis, input_rank, name)"
    , indentEight "keepdim = bool(kwargs.get(\"keepdim\", args[2] if len(args) > 2 and isinstance(args[2], bool) else False))"
    , indentEight "dtype = kwargs.get(\"dtype\", args[3] if len(args) > 3 else None)"
    , indentEight "if dtype is not None:"
    , indentEight "    raise NotImplementedError(f\"{name} with an explicit dtype changes scalar semantics outside the current TorchLean graph artifact\")"
    , indentEight "is_sum = name.startswith(\"aten.sum\") or name == \"sum\" or node.target is torch.sum"
    , indentEight "return {\"kind\": \"reduce_sum\" if is_sum else \"reduce_mean\", \"axes\": reduction_axes, \"keepdim\": keepdim}"
    , indentFour "if name.startswith(\"aten.softmax\") or \"softmax\" in name or node.target is F.softmax:"
    , indentEight "dtype = kwargs.get(\"dtype\", None)"
    , indentEight "if dtype is None and name.startswith(\"aten.softmax\") and len(args) > 2: dtype = args[2]"
    , indentEight "if dtype is not None and dtype is not False:"
    , indentEight "    raise NotImplementedError(\"softmax with an explicit dtype/cast is outside the current TorchLean graph artifact\")"
    , indentEight "rank = len(_node_shape(node))"
    , indentEight "return {\"kind\": \"softmax\", \"axis\": _normalize_axis(axis if axis is not None else -1, rank)}"
    , indentFour "if name.startswith(\"aten.reshape\") or name.startswith(\"aten.view\") or name in (\"reshape\", \"view\"):"
    , indentEight "return {\"kind\": \"reshape\", \"in_shape\": _shape_from_arg(args[0]) if args else [], \"out_shape\": _node_shape(node)}"
    , indentFour "if name == \"contiguous\":"
    , indentEight "s = _shape_from_arg(args[0]) if args else _node_shape(node)"
    , indentEight "return {\"kind\": \"reshape\", \"in_shape\": s, \"out_shape\": _node_shape(node)}"
    , indentFour "if name.startswith(\"aten.flatten\") or name == \"flatten\" or node.target is torch.flatten:"
    , indentEight "return _flatten_kind(_shape_from_arg(args[0]) if args else [], _node_shape(node))"
    , indentFour "if name.startswith(\"aten.permute\") or name == \"permute\":"
    , indentEight "perm = list(args[1]) if len(args) > 1 and isinstance(args[1], (tuple, list)) else [int(x) for x in args[1:]] if name == \"permute\" else list(kwargs.get(\"dims\", []))"
    , indentEight "rank = len(_node_shape(node))"
    , indentEight "return {\"kind\": \"permute\", \"perm\": [_normalize_axis(x, rank) for x in perm]}"
    , indentFour "if name.startswith(\"aten.cat\") or node.target is torch.cat:"
    , indentEight "rank = len(_node_shape(node))"
    , indentEight "dim = _normalize_axis(kwargs.get(\"dim\", args[1] if len(args) > 1 else 0), rank)"
    , indentEight "return {\"kind\": \"concat\", \"axis\": dim}"
    , indentFour "if name.startswith(\"aten.transpose\") or name == \"transpose\":"
    , indentEight "rank = len(_shape_from_arg(args[0])) if args else len(_node_shape(node))"
    , indentEight "d0 = _normalize_axis(args[1], rank); d1 = _normalize_axis(args[2], rank)"
    , indentEight "return {\"kind\": \"transpose\", \"axis1\": d0, \"axis2\": d1}"
    , indentFour "if name.startswith(\"aten.layer_norm\") or node.target is F.layer_norm:"
    , indentEight "weight = kwargs.get(\"weight\", args[2] if len(args) > 2 else None)"
    , indentEight "bias = kwargs.get(\"bias\", args[3] if len(args) > 3 else None)"
    , indentEight "eps = kwargs.get(\"eps\", args[4] if len(args) > 4 else 1e-5)"
    , indentEight "input_rank = len(_shape_from_arg(args[0])) if args else len(_node_shape(node))"
    , indentEight "normalized_shape = args[1] if len(args) > 1 else kwargs.get(\"normalized_shape\", ())"
    , indentEight "normalized_rank = len(normalized_shape) if isinstance(normalized_shape, (tuple, list, torch.Size)) else 1"
    , indentEight "weight = _resolve_tensor(weight) if weight is not None else torch.ones(normalized_shape)"
    , indentEight "bias = _resolve_tensor(bias) if bias is not None else torch.zeros(normalized_shape)"
    , indentEight "return {\"kind\": \"layernorm\", \"axis\": max(0, input_rank - normalized_rank), \"eps\": float(eps), \"gamma\": _tensor_values(weight), \"beta\": _tensor_values(bias)}"
    , indentFour "if name.startswith(\"aten.linear\") or node.target is F.linear: return {\"kind\": \"linear\"}"
    , indentFour "if \"batch_norm\" in name or node.target is F.batch_norm:"
    , indentEight "training = bool(kwargs.get(\"training\", args[5] if len(args) > 5 else False))"
    , indentEight "if training: raise NotImplementedError(\"training-mode batch_norm is outside the eval-mode TorchLean IR operation\")"
    , indentEight "running_mean = kwargs.get(\"running_mean\", args[1] if len(args) > 1 else None)"
    , indentEight "running_var = kwargs.get(\"running_var\", args[2] if len(args) > 2 else None)"
    , indentEight "if running_mean is None or running_var is None: raise NotImplementedError(\"batch_norm without running statistics is outside the eval-mode TorchLean IR operation\")"
    , indentEight "shape = _node_shape(node)"
    , indentEight "channels = int(shape[1]) if len(shape) >= 2 else 0"
    , indentEight "eps = float(kwargs.get(\"eps\", args[7] if len(args) > 7 else 1e-5))"
    , indentEight "running_mean = _resolve_tensor(kwargs.get(\"running_mean\", args[1] if len(args) > 1 else None))"
    , indentEight "running_var = _resolve_tensor(kwargs.get(\"running_var\", args[2] if len(args) > 2 else None))"
    , indentEight "weight = kwargs.get(\"weight\", args[3] if len(args) > 3 else None)"
    , indentEight "bias = kwargs.get(\"bias\", args[4] if len(args) > 4 else None)"
    , indentEight "weight = _resolve_tensor(weight) if weight is not None else torch.ones(channels)"
    , indentEight "bias = _resolve_tensor(bias) if bias is not None else torch.zeros(channels)"
    , indentEight "return {\"kind\": \"batch_norm_eval\", \"channel_axis\": 1, \"channels\": channels, \"eps\": eps, \"gamma\": _tensor_values(weight), \"beta\": _tensor_values(bias), \"mean\": _tensor_values(running_mean), \"var\": _tensor_values(running_var)}"
    , indentFour "if any(name.startswith(f\"aten.conv{d}d\") for d in (1, 2, 3)) or node.target in (F.conv1d, F.conv2d, F.conv3d):"
    , indentEight "weight = args[1] if len(args) > 1 else None"
    , indentEight "wshape = _shape_of(weight.meta.get(\"val\") if hasattr(weight, \"meta\") else weight)"
    , indentEight "rank = max(0, len(wshape) - 2)"
    , indentEight "input_rank = len(_shape_from_arg(args[0])) if args else 0"
    , indentEight "if input_rank not in (rank + 1, rank + 2): raise NotImplementedError(f\"convolution expected rank {rank + 1} or {rank + 2}, got {input_rank}\")"
    , indentEight "channel_axis = input_rank - rank - 1"
    , indentEight "stride = _spatial_tuple(kwargs.get(\"stride\", args[3] if len(args) > 3 else 1), rank, 1)"
    , indentEight "padding = _spatial_tuple(kwargs.get(\"padding\", args[4] if len(args) > 4 else 0), rank, 0)"
    , indentEight "dilation = _spatial_tuple(kwargs.get(\"dilation\", args[5] if len(args) > 5 else 1), rank, 1)"
    , indentEight "groups = int(kwargs.get(\"groups\", args[6] if len(args) > 6 else 1))"
    , indentEight "out_channels = int(wshape[0]) if len(wshape) >= 2 else 0"
    , indentEight "in_channels = int(wshape[1]) * groups if len(wshape) >= 2 else 0"
    , indentEight "return {\"kind\": \"conv\", \"spatial_rank\": rank, \"kernel\": [int(v) for v in wshape[2:]], \"stride\": stride, \"padding\": padding, \"padding_after\": padding, \"dilation\": dilation, \"groups\": groups, \"channel_axis\": channel_axis, \"in_channels\": in_channels, \"out_channels\": out_channels}"
    , indentFour "if any(name.startswith(f\"aten.max_pool{d}d\") for d in (1, 2, 3)) or node.target in (F.max_pool1d, F.max_pool2d, F.max_pool3d):"
    , indentEight "rank = 1 if name.startswith(\"aten.max_pool1d\") or node.target is F.max_pool1d else 2 if name.startswith(\"aten.max_pool2d\") or node.target is F.max_pool2d else 3"
    , indentEight "kernel = _spatial_tuple(args[1] if len(args) > 1 else kwargs.get(\"kernel_size\", 1), rank, 1)"
    , indentEight "stride_arg = kwargs.get(\"stride\", args[2] if len(args) > 2 else None)"
    , indentEight "stride = _spatial_tuple(stride_arg if stride_arg not in (None, []) else kernel, rank, 1)"
    , indentEight "padding = _spatial_tuple(kwargs.get(\"padding\", args[3] if len(args) > 3 else 0), rank, 0)"
    , indentEight "dilation = _spatial_tuple(kwargs.get(\"dilation\", args[4] if len(args) > 4 else 1), rank, 1)"
    , indentEight "ceil_mode = bool(kwargs.get(\"ceil_mode\", args[5] if len(args) > 5 else False))"
    , indentEight "if dilation != [1] * rank: raise NotImplementedError(\"dilated max pooling is outside the current TorchLean IR import subset\")"
    , indentEight "if ceil_mode: raise NotImplementedError(\"max pooling with ceil_mode=True is outside the current TorchLean IR import subset\")"
    , indentEight "return {\"kind\": \"max_pool\", \"spatial_rank\": rank, \"kernel\": kernel, \"stride\": stride, \"padding\": padding}"
    , indentFour "if any(name.startswith(f\"aten.avg_pool{d}d\") for d in (1, 2, 3)) or node.target in (F.avg_pool1d, F.avg_pool2d, F.avg_pool3d):"
    , indentEight "rank = 1 if name.startswith(\"aten.avg_pool1d\") or node.target is F.avg_pool1d else 2 if name.startswith(\"aten.avg_pool2d\") or node.target is F.avg_pool2d else 3"
    , indentEight "kernel = _spatial_tuple(args[1] if len(args) > 1 else kwargs.get(\"kernel_size\", 1), rank, 1)"
    , indentEight "stride_arg = kwargs.get(\"stride\", args[2] if len(args) > 2 else None)"
    , indentEight "stride = _spatial_tuple(stride_arg if stride_arg not in (None, []) else kernel, rank, 1)"
    , indentEight "padding = _spatial_tuple(kwargs.get(\"padding\", args[3] if len(args) > 3 else 0), rank, 0)"
    , indentEight "ceil_mode = bool(kwargs.get(\"ceil_mode\", args[4] if len(args) > 4 else False))"
    , indentEight "count_include_pad = bool(kwargs.get(\"count_include_pad\", args[5] if len(args) > 5 else True))"
    , indentEight "divisor_override = kwargs.get(\"divisor_override\", args[6] if len(args) > 6 else None)"
    , indentEight "if ceil_mode: raise NotImplementedError(\"average pooling with ceil_mode=True is outside the current TorchLean IR import subset\")"
    , indentEight "if any(padding) and not count_include_pad: raise NotImplementedError(\"padded average pooling with count_include_pad=False is outside the current TorchLean IR import subset\")"
    , indentEight "if divisor_override is not None: raise NotImplementedError(\"average pooling with divisor_override is outside the current TorchLean IR import subset\")"
    , indentEight "return {\"kind\": \"avg_pool\", \"spatial_rank\": rank, \"kernel\": kernel, \"stride\": stride, \"padding\": padding}"
    , indentFour "if _is_getitem(node):"
    , indentEight "idx = int(args[1]) if len(args) > 1 and isinstance(args[1], int) else 0"
    , indentEight "return {\"kind\": \"tuple_getitem\", \"index\": idx}"
    , indentFour "if _is_getattr(node):"
    , indentEight "attr = args[1] if len(args) > 1 else \"<unknown>\""
    , indentEight "raise NotImplementedError(f\"unsupported PyTorch attribute projection: {attr}. If this came from a tuple-returning op such as torch.sort(...).values, add a value-graph/lowering rule for that producer instead of treating the attribute as an ordinary tensor op.\")"
    , indentFour "raise NotImplementedError(f\"unsupported PyTorch op: {name}\")"
    , ""
    , "def _graph_is_lowerable(graph, model):"
    , indentFour "try:"
    , indentEight "for node in graph.nodes:"
    , indentEight "    if node.op in (\"placeholder\", \"get_attr\", \"output\"):"
    , indentEight "        continue"
    , indentEight "    if len(getattr(node, \"users\", {})) == 0:"
    , indentEight "        continue"
    , indentEight "    if _tuple_shapes_of_node(node):"
    , indentEight "        _tuple_kind(node, model)"
    , indentEight "    elif node.op in (\"call_function\", \"call_method\", \"call_module\"):"
    , indentEight "        _lower_kind(node, model)"
    , indentEight "    else:"
    , indentEight "        return False"
    , indentFour "except NotImplementedError:"
    , indentEight "return False"
    , indentFour "return True"
    , ""
    , "def _capture(model, example, require_torch_export=False):"
    , indentFour "global _TENSOR_VALUES"
    , indentFour "_TENSOR_VALUES = {}"
    , indentFour "if " ++ pyBool opts.preferTorchExport ++ ":"
    , indentEight "try:"
    , indentEight "    ep = torch.export.export(model, (example,))"
    , indentEight "    # ExportedProgram lifts parameters, buffers, and constants into graph"
    , indentEight "    # placeholders. Their order is not a user-input contract, so classify"
    , indentEight "    # placeholders through graph_signature rather than taking the first one."
    , indentEight "    user_input_names = {"
    , indentEight "        spec.arg.name"
    , indentEight "        for spec in ep.graph_signature.input_specs"
    , indentEight "        if getattr(spec.kind, \"name\", \"\") == \"USER_INPUT\""
    , indentEight "    }"
    , indentEight "    state = dict(ep.state_dict)"
    , indentEight "    constants = dict(getattr(ep, 'constants', {}))"
    , indentEight "    for spec in ep.graph_signature.input_specs:"
    , indentEight "        if getattr(spec.kind, 'name', '') != 'USER_INPUT':"
    , indentEight "            target = getattr(spec, 'target', None)"
    , indentEight "            value = state.get(target, constants.get(target, None))"
    , indentEight "            if isinstance(value, torch.Tensor): _TENSOR_VALUES[spec.arg.name] = value"
    , indentEight "    if _graph_is_lowerable(ep.graph, model):"
    , indentEight "        return ep.graph, user_input_names"
    , indentEight "except Exception:"
    , indentEight "    if require_torch_export:"
    , indentEight "        raise"
    , indentFour "if require_torch_export:"
    , indentEight "raise NotImplementedError(\"torch.export produced operators outside the current TorchLean import subset\")"
    , indentFour "from torch.fx import symbolic_trace"
    , indentFour "from torch.fx.passes.shape_prop import ShapeProp"
    , indentFour "gm = symbolic_trace(model)"
    , indentFour "ShapeProp(gm).propagate(example)"
    , indentFour "for node in gm.graph.nodes:"
    , indentEight "if node.op == 'get_attr':"
    , indentEight "    value = gm"
    , indentEight "    for part in str(node.target).split('.'): value = getattr(value, part)"
    , indentEight "    if isinstance(value, torch.Tensor): _TENSOR_VALUES[node.name] = value"
    , indentFour "return gm.graph, None"
    , ""
    , s!"def {opts.functionName}(model, example, json_path: str, require_torch_export=False):"
    , indentFour "graph, user_input_names = _capture(model, example, require_torch_export)"
    , indentFour "nodes = []"
    , indentFour "node_to_id = {}"
    , indentFour "output_ids = None"
    , indentFour "input_id = None"
    , indentFour "for node in graph.nodes:"
    , indentEight "if node.op == \"output\":"
    , indentEight "    refs = _node_refs(node.args, node_to_id)"
    , indentEight "    if not refs:"
    , indentEight "        raise NotImplementedError(\"TorchLean graph import requires at least one tensor output\")"
    , indentEight "    output_ids = refs"
    , indentEight "    continue"
    , indentEight "if len(getattr(node, \"users\", {})) == 0:"
    , indentEight "    # FX often leaves dead tuple projections behind, e.g. attention weights from"
    , indentEight "    # `y, _ = mha(...)`. They are not part of the exported value, so we omit them"
    , indentEight "    # instead of forcing every unused container projection to have a tensor lowering."
    , indentEight "    node_to_id[node] = None"
    , indentEight "    continue"
    , indentEight "if node.op in (\"get_attr\",):"
    , indentEight "    continue"
    , indentEight "if node.op == \"placeholder\" and user_input_names is not None:"
    , indentEight "    if node.name not in user_input_names:"
    , indentEight "        # Parameters, buffers, constants, and effect tokens live outside"
    , indentEight "        # TorchLean's single user-input tensor dataflow graph."
    , indentEight "        node_to_id[node] = None"
    , indentEight "        continue"
    , indentEight "node_id = len(nodes)"
    , indentEight "node_to_id[node] = node_id"
    , indentEight "shape = _node_shape(node)"
    , indentEight "tuple_shapes = _tuple_shapes_of_node(node)"
    , indentEight "value_meta = {\"value_kind\": \"tuple\", \"tuple_shapes\": tuple_shapes} if tuple_shapes else {\"value_kind\": \"tensor\", \"shape\": shape}"
    , indentEight "if node.op == \"placeholder\":"
    , indentEight "    if input_id is not None:"
    , indentEight "        raise NotImplementedError(\"TorchLean graph import currently supports one user input\")"
    , indentEight "    kind = {\"kind\": \"input\"}"
    , indentEight "    parents = []"
    , indentEight "    input_id = node_id"
    , indentEight "elif tuple_shapes:"
    , indentEight "    # Preserve tuple/list-valued FX nodes in the import artifact. They are lowered to the"
    , indentEight "    # tensor-only TorchLean IR only when a later semantic lowering rule exists."
    , indentEight "    kind = _tuple_kind(node, model)"
    , indentEight "    parents = _node_refs((node.args, node.kwargs), node_to_id)"
    , indentEight "elif node.op in (\"call_function\", \"call_method\", \"call_module\"):"
    , indentEight "    kind = _lower_kind(node, model)"
    , indentEight "    parents = _node_refs((node.args, node.kwargs), node_to_id)"
    , indentEight "else:"
    , indentEight "    raise NotImplementedError(f\"unsupported FX node op: {node.op}\")"
    , indentEight "entry = {\"id\": node_id, \"parents\": parents, **value_meta, **kind}"
    , indentEight "if " ++ pyBool opts.includeDebugTargets ++ ":"
    , indentEight "    entry[\"debug_target\"] = _target_name(node.target)"
    , indentEight "nodes.append(entry)"
    , indentFour "if input_id is None or output_ids is None:"
    , indentEight "raise RuntimeError(\"could not identify graph input/output\")"
    , indentFour "payload = {\"format\": FORMAT, \"input_id\": input_id, \"output_ids\": output_ids, \"nodes\": nodes}"
    , indentFour "with open(json_path, \"w\", encoding=\"utf-8\") as f:"
    , indentEight "json.dump(payload, f, indent=2, sort_keys=True)"
    , indentFour "return payload"
    , ""
    , "def main():"
    , indentFour "parser = argparse.ArgumentParser(description=\"Export a PyTorch nn.Module to TorchLean IR JSON\")"
    , indentFour "parser.add_argument(\"module\", help=\"Python file containing the model class/constructor\")"
    , indentFour "parser.add_argument(\"ctor\", help=\"Zero-argument model class or constructor name\")"
    , indentFour "parser.add_argument(\"json\", help=\"Output graph JSON path\")"
    , indentFour "parser.add_argument(\"--example-shape\", required=True, help=\"Comma-separated example input shape, e.g. 1,4\")"
    , indentFour "parser.add_argument(\"--require-torch-export\", action=\"store_true\", help=\"Fail instead of falling back to FX\")"
    , indentFour "args = parser.parse_args()"
    , indentFour "shape = tuple(int(x) for x in args.example_shape.split(',') if x)"
    , indentFour "model = _load_model(args.module, args.ctor)"
    , indentFour "example = torch.randn(*shape)"
    , indentFour s!"payload = {opts.functionName}(model, example, args.json, args.require_torch_export)"
    , indentFour "print(f\"wrote {len(payload['nodes'])} TorchLean IR nodes to {args.json}\")"
    , ""
    , "if __name__ == \"__main__\":"
    , indentFour "main()"
    ]

end TorchExport
end PyTorch
end Export
