/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Tensor.Constructors

/-!
# Tensor Literal Syntax

Compile-time checked tensor literals. Import `NN.Tensor` for these macros together with the rest of
the public tensor API.
-/

@[expose] public section

namespace TorchLean.Tensor

open Lean

/-- Close the flat-array size goals generated by tensor literal macros. -/
macro "tensor_size" : tactic =>
  `(tactic| first
    | (simp [List.prod]; dsimp; decide)
    | decide
    | simp [List.prod])

/-- Construct a tensor from dimensions and an array whose literal size can be proved at elaboration. -/
macro "tensorOfArray!" dims:term:max xs:term:max : term =>
  `(TorchLean.Tensor.Internal.fromArray (dims := $dims) (xs := $xs) (by tensor_size))

/-- Typed form of `tensorOfArray!`. -/
macro "tensorOfArray!" "(" name:ident ":=" elemTy:term ")" dims:term:max xs:term:max : term => do
  if name.getId != `ty then
    Lean.Macro.throwErrorAt name "tensorOfArray!: expected `(ty := <type>)`"
  `(TorchLean.Tensor.Internal.fromArray (α := $elemTy) (dims := $dims) (xs := $xs)
      (by tensor_size))

namespace TensorLit

/-- Parse a rectangular nested list literal into dimensions and row-major scalar leaves. -/
private meta partial def parseNested (t : Syntax) : MacroM (List Nat × List Syntax) := do
  match t with
  | `([$ts,*]) =>
      let es := ts.elemsAndSeps
      let mut elems : Array Syntax := #[]
      for i in List.finRange es.size do
        if i.val % 2 = 0 then
          elems := elems.push (es[i.val]!)
      if elems.isEmpty then
        pure ([0], [])
      else
        let parsed : List (List Nat × List Syntax) ← elems.toList.mapM parseNested
        match parsed with
        | [] => pure ([0], [])
        | (dims0, flat0) :: rest =>
            for (dims, _) in rest do
              if dims != dims0 then
                Macro.throwErrorAt t "tensor!: ragged or mixed-depth nested lists are not supported"
            let flat := rest.foldl (fun acc p => acc ++ p.snd) flat0
            pure (elems.size :: dims0, flat)
  | _ => pure ([], [t])

end TensorLit

/-- Construct a typed tensor from a rectangular nested list literal. -/
macro "tensor!" "(" name:ident ":=" elemTy:term ")" xs:term:max : term => do
  if name.getId != `ty then
    Lean.Macro.throwErrorAt name "tensor!: expected `(ty := <type>)`"
  let (dims, flat) ← TensorLit.parseNested xs
  let dimsElems : Array (TSyntax `term) :=
    dims.toArray.map (fun n => ⟨Syntax.mkNumLit (toString n)⟩)
  let flatElems : Array (TSyntax `term) := flat.toArray.map fun stx => ⟨stx⟩
  let dimsSep := Syntax.TSepArray.ofElems (sep := ",") dimsElems
  let flatSep := Syntax.TSepArray.ofElems (sep := ",") flatElems
  let dimsTerm ← `(term| [$(dimsSep),*])
  let flatTerm ← `(term| #[$(flatSep),*])
  match dims with
  | [n] =>
      let nTerm : TSyntax `term := ⟨Syntax.mkNumLit (toString n)⟩
      `(Spec.Tensor.ofArrayExact (α := $elemTy) (n := $nTerm) $flatTerm (by tensor_size))
  | _ =>
      `(TorchLean.Tensor.Internal.fromArray (α := $elemTy) (dims := $dimsTerm) (xs := $flatTerm)
          (by tensor_size))

/-- Construct a tensor from a rectangular nested list literal, inferring its element type. -/
macro:max "tensor!" xs:term:max : term => do
  let (dims, flat) ← TensorLit.parseNested xs
  let dimsElems : Array (TSyntax `term) :=
    dims.toArray.map (fun n => ⟨Syntax.mkNumLit (toString n)⟩)
  let flatElems : Array (TSyntax `term) := flat.toArray.map fun stx => ⟨stx⟩
  let dimsSep := Syntax.TSepArray.ofElems (sep := ",") dimsElems
  let flatSep := Syntax.TSepArray.ofElems (sep := ",") flatElems
  let dimsTerm ← `(term| [$(dimsSep),*])
  let flatTerm ← `(term| #[$(flatSep),*])
  match dims with
  | [n] =>
      let nTerm : TSyntax `term := ⟨Syntax.mkNumLit (toString n)⟩
      `(Spec.Tensor.ofArrayExact (n := $nTerm) $flatTerm (by tensor_size))
  | _ =>
      `(TorchLean.Tensor.Internal.fromArray (dims := $dimsTerm) (xs := $flatTerm)
          (by tensor_size))

end TorchLean.Tensor
