import VersoManual
import VersoBlueprint

open Verso.Genre Manual

#doc (Manual) "The Parity Harness: One Fixture, the Whole Pipeline, Decision-Level Stochastic Match (S8)" =>
%%%
tag := "kernelflows-parity-harness"
%%%

Steps S1–S7 each verified one stage of the KernelFlows / Computational-Hypergraph-Discovery numerical
core — the kernel build, the positive-definiteness, the four cross-validation losses, the predictive
variance, the optimizer step, the inverse-form gradients, and Jacobi's formula for `ρ_MLE` — *each on
its own fixture*. S8 is the *parity harness*: the Year-2 deliverable that drives *one shared problem
through the entire pipeline at once* and checks every stage against the reference implementations. It
proves nothing new about the mathematics; its job is to certify that the *composition* of the verified
specs reproduces KernelFlows.jl and the CHD `Z_test` — the deterministic stages bit-for-bit, the
stochastic stage at the level of its *decision*.

# Why a harness, and not another theorem

The correctness of each stage was settled in S1–S7 over `ℝ`. What was *not* yet exercised is the claim
the proposal actually makes to a user: *run this port and it behaves like the reference*. That is an
end-to-end, executable, `Float`-level statement about the composed pipeline — a different obligation
from the per-stage proofs, and the right one for a Year-2 validation deliverable. So S8 lives entirely
in `NN.Examples.KernelFlows.Parity`: a single fixture (the verbatim KernelFlows.jl S1 kernel tile — 4
points in `ℝ²`, `nXlinear = 1`, `logθ = [0, 0.5, −1, −3]` — plus a label `y` and a test vector) flows

$$`\text{kernel build} \to \text{losses} \to \text{gradients} \to \text{optimizer step} \to \text{conditional variance} \to \text{eig} \to Z\text{-test},`

and each arrow is checked against a golden generated by the reference's exact arithmetic.

# The deterministic float-path: bit-for-bit, and the composition is the point

`Deterministic.lean` matches every deterministic stage to the float-path tolerance `1e-8` — in practice
to `0`, exactly, on this fixture. The kernel tile reproduces the verbatim KernelFlows.jl
`kernel_matrix` (the Lean exact-distance build differs from the `5·eps`-floored reference only through
the Matérn flat top, `~10⁻¹⁵` — the S1 finding); the four losses match `loss_functions.jl`; the kernel
derivative tiles match `Matern32_αgrad!`; the loss gradients and the Jacobi `∂logdet` match the
S6/S7 closed forms; the conditional variance matches `conditional_variance.jl`.

The *composition* is what a harness adds over the per-stage checks: the optimizer step is driven by the
*actual* `∇ρ_MLE` computed one stage upstream, so a single AMSGrad update of `logθ` — and a fixed-step
SGD update — is matched against `optimizers.jl` *as the pipeline would produce it*, gradient feeding
optimizer feeding the next iterate. A stage that silently disagreed with the reference only when fed a
real upstream value (rather than a hand-picked test input) would be caught here and nowhere else. The
*negative controls* give the metric teeth: the tile at perturbed hyperparameters drifts off the golden
by `≫ 1e-8`, a loss checked against the wrong stage's golden is rejected, and one AMSGrad step along
the *sign-flipped* gradient lands far from the golden iterate.

# The stochastic `Z_test`: parity is a property of the decision, not the draws

The CHD edge test is *stochastic*. It scores the observed `noise` against the null distribution of the
*same* statistic under `N` random draws (`jax.random.normal`) and keeps the edge when
`noise < Z_{low}`, the null's 5th percentile. Demanding bit-for-bit parity against a particular RNG
stream is neither possible nor meaningful — *what CHD consumes is the decision*: the recovered kernel /
edge set. `Stochastic.lean` matches parity at exactly that level, and this is the one genuinely new
*idea* S8 contributes.

It rests on a structural fact worth stating plainly: the `noise` statistic is a *spectral function of
`Ω`*,

$$`\mathrm{noise}(g) = \frac{g^{\top} f(\Omega)\, g}{g^{\top} h(\Omega)\, g}, \qquad f(\Omega)=\sum_i r_i^2 v_i v_i^{\top},\ \ h(\Omega)=\sum_i r_i v_i v_i^{\top},\ \ r_i=\tfrac{\gamma}{\lambda_i+\gamma},`

so it depends on `Ω` and the data `g` *only* — not on the eigenbasis. That is why the verified Jacobi
eigensolver and the reference's LAPACK eigensolver agree on every null `noise` to machine precision
even though their eigenvectors differ in sign and order: the harness matches `Z_{low}`/`Z_{high}` and
the observed signal `noise` to the golden to `1e-7` despite a completely different eigendecomposition
underneath.

On that deterministic backbone the decision-level claim is checked directly: the signal-aligned edge is
recovered under *two independent* null tiles — different deterministic generators standing in for two
`jax.random` keys — and the verdict is *identical*. The recovered kernel set (via
`MinNoiseKernelChooser`) is identical too. The harness then exhibits *why*: the signal `noise` clears
each null's lower tail by a wide *separation margin* (`Z_{low} − \mathrm{noise} \approx 0.14` and
`0.23`), so no re-draw can flip it. The *negative controls* keep this honest — a `noise` placed *inside*
the null band is correctly not an edge, and a deliberately *borderline* signal, parked between the two
tiles' thresholds, is shown to be *not* RNG-invariant (significant under one tile, not the other). So
the invariance the harness certifies is a real property of *well-separated* edges, not an artifact of
the test always saying "yes."

# What S8 surfaces: the port reproduces the reference where it is determinate and decides like it where it is not

The harness draws the honest line the formalization has been chasing since S1. Where the computation is
*determinate* — the kernel, the losses, the gradients, the optimizer arithmetic, the predictive
variance — the Lean port reproduces KernelFlows.jl to the last representable bit, *composed*, not just
stage by stage. Where it is *stochastic* — the edge test — bit-parity is the wrong target, and the
harness instead certifies that the port *decides* the same graph structure as the reference and stays
RNG-invariant by a quantified margin. That pairing — exact where it can be, decision-level where it must
be — is the parity guarantee a downstream CHD user actually needs, and it now runs green on every build.

# Executable witnesses

`NN.Examples.KernelFlows.Parity` is the harness. `Parity.Common` holds the shared fixture and the parity
assertion helpers; `Parity.Deterministic` runs the float-path pipeline (kernel, four losses, derivative
tiles, four loss gradients, the Jacobi `∂logdet`, one AMSGrad and one SGD step on the real `∇ρ_MLE`, the
conditional variance) each against its golden, plus the three negative controls; `Parity.Stochastic`
runs the `Z_test` decision under two independent null tiles, the separation-margin witnesses, and the
two borderline negative controls. Every check is a `#eval` over `Float`, with no unproved goals, omega-free, green
on `lake build NN.Examples.KernelFlows`.
